### ISSUE TITLE
Can't hit https://api.github.com via Neko

### ISSUE THREAD

**Issue by mikestead** [tong/hxssl#34] opened 2014-09-18 23:41 UTC
Hi, i'm trying to play with the github api via neko but can't seem to hit any of its endpoints.
```
var loader = new haxe.Http("https://api.github.com");
loader.setHeader("Accept", "application/vnd.github.v3+json");
loader.onData = function(value:String) { trace("Success: " + value); };		
loader.onError = function(value:String) { trace("Error: " + value); };
loader.request();
```
Outputs: `Error: Custom((1) : An unknown error has occurred.)`

Using Haxe 3.1.3. I've tried using hxssl `3.0.0-alpha` and building master but no joy. Any ideas?

**Comment by Simn** [comment] 2015-06-05 12:07
Hi Mike,

I just came across the same problem. Did you ever find a solution?

**Comment by mikestead** [comment] 2015-06-05 12:11
Nope sorry I never did

**Comment by Blank101** [comment] 2015-06-05 19:51
What OS?

**Comment by Simn** [comment] 2015-06-05 19:58
Windows for me.

**Comment by mikestead** [comment] 2015-06-05 21:08
OS X for me

**Comment by Blank101** [comment] 2015-06-05 21:13
Have either of you tried the latest git version? A much more detailed error should be going to stderr now.

**Comment by Simn** [comment] 2015-06-05 21:14
Yes I am on latest git.

**Comment by tjrhodes** [comment] 2015-08-07 14:41
Hi this is happening to me too, can you confirm "Custom((1) : An unknown error has occurred.)" is an hxssl error?

@Simn @mikestead ether of you manage to fix/workaround this?

**Comment by Blank101** [comment] 2015-10-05 23:41
Just an update on this. I believe this error is being caused by failed certificate validation for OSX and Windows. Will be able to fix once https://github.com/HaxeFoundation/haxe/pull/4569 is merged.

**Comment by Blank101** [comment] 2015-10-06 19:39
Can someone verify newest hxssl/haxe builds fixes this problem? Travis unit tests are passing on OS X now.

**Comment by Blank101** [comment] 2015-10-07 16:32
Think I'll just close this unless someone tells me otherwise.

**Closed by Blank101** 2015-10-07 16:32 UTC

**Comment by Atry** [comment] 2016-02-09 18:11
It became a `Error:  Eof` for Haxe 3.2.1 and hxssl master branch
